HISTORY_MODEL_OPTION_GROUPED = "grouped"
HISTORY_MODEL_OPTION_SINGLE = "single"

HISTORY_MODEL_OPTIONS = (
    (HISTORY_MODEL_OPTION_GROUPED, "Grouped"),
    (HISTORY_MODEL_OPTION_SINGLE, "Single"),
)